name: Run calkit pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
# env:
  # MLM_LICENSE_TOKEN: ${{ secrets.MatlabBatchToken }}
  # MLM_LICENSE_FILE: ${{ secrets.MATLAB_LICENSE_FILE }}:27000
permissions:
  contents: write

# Make sure we only ever run one per branch so we don't have issues pushing
# after running the pipeline
concurrency:
  group: calkit-run-${{ github.ref }}
  cancel-in-progress: false

jobs:
  main:
    name: Run
    runs-on: self-hosted
    timeout-minutes: 1440 # 24 hours
    steps:
      - uses: actions/checkout@v4
        with:
          # For PRs, checkout the head ref to avoid detached HEAD
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Checkout WEC-Sim
        uses: actions/checkout@v4
        if: always()
        with:
          repository: WEC-Sim/WEC-Sim
          path: WEC-Sim
          ref: dev
      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Install Calkit
        run: uv tool install calkit-python #git+https://github.com/rebeccamccabe/calkit.git@save-successful-stages
      # - name: Setup matlab
      #   uses: matlab-actions/setup-matlab@v2
      #   with:
      #     cache: true
      #     release: R2024b
      #     products: >
      #       Parallel_Computing_Toolbox
      #       Global_Optimization_Toolbox
      #       Optimization_Toolbox
      #       Statistics_and_Machine_Learning_Toolbox
      #       MATLAB_Report_Generator
      #       Simulink
      #       Simscape
      #       Simscape_Multibody
      - name: Add MATLAB to PATH
        run: echo "/usr/local/MATLAB/R2024b/bin" >> $GITHUB_PATH
      # - name: test matlab can run
      #   run: matlab -batch "disp('Matlab is working')"
      # - name: test matlab license server
      #   run: | # Mask the license server IP address in logs
      #     echo "::add-mask::$(dig +short ${{ secrets.MATLAB_LICENSE_FILE }} | tail -n 1)" 
      #     curl -v --max-time 5 telnet://${{ env.MLM_LICENSE_FILE }}
      #   if: always()
      - name: Run Calkit
        id: run_calkit
        uses: rebeccamccabe/run-action@v2
        with:
          dvc_token: ${{ secrets.CALKIT_DVC_TOKEN }}
          run_args: --ignore-errors --log
          save: false
      - name: DVC push
        if: always()
        run: calkit save dvc.lock dvc.yaml -m "Run pipeline"
      - if: ${{ steps.run_calkit.outcome == 'failure' }}
        run: |
          echo "Errors from latex:"
          grep -E "^!" pubs/applied-ocean-research-model/aux/main.log
          grep -E "^!" pubs/renewable-energy-mdo/aux/mdocean.log